<?php

declare(strict_types=1);

namespace Vortos\Backup\DR;

use Vortos\Backup\Domain\ObjectLockPolicy;
use Vortos\Backup\Drill\DrillReportStoreInterface;

final class DrRunbookGenerator
{
    public function __construct(
        private readonly RecoveryObjectives $objectives,
        private readonly ?ObjectLockPolicy $lockPolicy,
        private readonly DrillReportStoreInterface $reportStore,
        private readonly string $primaryStore,
        private readonly ?string $secondaryStore,
        private readonly string $keyProviderName,
    ) {}

    public function generate(string $environment): string
    {
        $latestDrill = $this->reportStore->latest('postgres', $environment);
        $measuredRto = $latestDrill !== null ? $latestDrill->rtoMs : null;

        $lines = [];
        $lines[] = '# DR Runbook — ' . $environment;
        $lines[] = '';
        $lines[] = '> Auto-generated by `vortos backup:dr-runbook`. Regenerated on each run.';
        $lines[] = '';

        $lines[] = '## Recovery Objectives';
        $lines[] = '';
        $lines[] = sprintf('- **RPO:** %d seconds (%s)', $this->objectives->rpoSeconds, $this->humanDuration($this->objectives->rpoSeconds));
        $lines[] = sprintf('- **RTO target:** %d seconds (%s)', $this->objectives->rtoSeconds, $this->humanDuration($this->objectives->rtoSeconds));
        if ($measuredRto !== null) {
            $lines[] = sprintf('- **Last measured RTO:** %dms (%s)', $measuredRto, $this->humanDuration((int) ($measuredRto / 1000)));
            if ($this->objectives->rtoExceeded($measuredRto)) {
                $lines[] = '- **WARNING:** Measured RTO exceeds target.';
            }
        }
        $lines[] = '';

        $lines[] = '## Storage';
        $lines[] = '';
        $lines[] = sprintf('- **Primary store:** `%s`', $this->primaryStore);
        if ($this->secondaryStore !== null) {
            $lines[] = sprintf('- **Secondary store (3-2-1):** `%s`', $this->secondaryStore);
        }
        $lines[] = '';

        $lines[] = '## Key Custody';
        $lines[] = '';
        $lines[] = sprintf('- **Key provider:** `%s`', $this->keyProviderName);
        $lines[] = '- **Wrap key (public):** `VORTOS_BACKUP_AGE_RECIPIENT` (on app host)';
        $lines[] = '- **Unwrap identity (private):** `VORTOS_BACKUP_AGE_IDENTITY` (**off-host**, restore/drill host only)';
        $lines[] = '';

        if ($this->lockPolicy !== null) {
            $lines[] = '## Object Lock';
            $lines[] = '';
            $lines[] = sprintf('- **Mode:** %s', $this->lockPolicy->mode);
            $lines[] = sprintf('- **Retention:** %d days', $this->lockPolicy->retentionDays);
            $lines[] = sprintf('- **Legal hold:** %s', $this->lockPolicy->legalHold ? 'yes' : 'no');
            $lines[] = '';
        }

        $lines[] = '## Restore Steps';
        $lines[] = '';
        $lines[] = '1. Ensure `VORTOS_BACKUP_AGE_IDENTITY` is set on the restore host.';
        $lines[] = '2. Ensure `VORTOS_BACKUP_DRILL_DSN` points to the target (non-production) database.';
        $lines[] = '3. Run: `vortos backup:restore --engine=postgres --env=' . $environment . ' --confirm`';
        $lines[] = '4. Verify: `vortos backup:drill --engine=postgres --env=' . $environment . '`';
        $lines[] = '';

        $lines[] = '## Drill Schedule';
        $lines[] = '';
        $lines[] = '- **Daily shallow decrypt-verify:** confirms KEK/cipher integrity without full restore.';
        $lines[] = '- **Weekly full drill:** provision → restore → invariant checks → measured RTO.';
        $lines[] = '';

        return implode("\n", $lines) . "\n";
    }

    private function humanDuration(int $seconds): string
    {
        if ($seconds < 60) {
            return $seconds . 's';
        }
        if ($seconds < 3600) {
            return sprintf('%dm %ds', intdiv($seconds, 60), $seconds % 60);
        }

        return sprintf('%dh %dm', intdiv($seconds, 3600), intdiv($seconds % 3600, 60));
    }
}
