<?php

declare(strict_types=1);

namespace Vortos\Iac\Tests\Exporter;

use PHPUnit\Framework\TestCase;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Vortos\Foundation\Config\Env;
use Vortos\Iac\Attribute\RegisterTerraformExporter;
use Vortos\Iac\DependencyInjection\Compiler\InfraConfigCompilerPass;
use Vortos\Iac\Definition\AbstractExporterDefinition;
use Vortos\Iac\Exporter\Kafka\KafkaProvider;
use Vortos\Iac\Exporter\Kafka\KafkaTopicsExporter;
use Vortos\Iac\Exporter\Kafka\KafkaTopicsExporterDefinition;
use Vortos\Iac\Exporter\Kafka\Mapper\ConfluentTopicMapper;
use Vortos\Iac\Exporter\Kafka\Mapper\MongeyKafkaTopicMapper;
use Vortos\Messaging\Attribute\MessagingConfig;
use Vortos\Messaging\Attribute\RegisterTransport;
use Vortos\Messaging\DependencyInjection\Compiler\MessagingConfigCompilerPass;
use Vortos\Messaging\Definition\Transport\AbstractTransportDefinition;
use Vortos\Messaging\Driver\Kafka\Definition\KafkaTransportDefinition;

#[MessagingConfig]
final class IacKafkaMessagingFixture
{
    #[RegisterTransport]
    public function ordersTransport(): AbstractTransportDefinition
    {
        return KafkaTransportDefinition::create('orders.placed')
            ->dsn(Env::string('KAFKA_BROKERS'))
            ->topic('orders.placed')
            ->partitions(Env::int('KAFKA_PARTITIONS', default: 12))
            ->replicationFactor(3)
            ->topicConfig([
                'retention.ms' => Env::int('KAFKA_RETENTION_MS', default: 604800000),
                'cleanup.policy' => 'delete',
            ]);
    }

    #[RegisterTransport]
    public function debugTransport(): AbstractTransportDefinition
    {
        return KafkaTransportDefinition::create('debug.events')
            ->dsn(Env::string('KAFKA_BROKERS'))
            ->topic('debug.events');
    }
}

#[\Vortos\Iac\Attribute\InfraConfig]
final class IacKafkaInfraFixture
{
    #[RegisterTerraformExporter]
    public function kafkaTopics(): KafkaTopicsExporterDefinition
    {
        return KafkaTopicsExporterDefinition::create('kafka-topics')
            ->provider(KafkaProvider::Confluent)
            ->clusterRef('confluent_kafka_cluster.main')
            ->exclude('debug.*')
            ->outputFile('infra/kafka_topics.tf.json');
    }
}

final class KafkaTopicsExportTest extends TestCase
{
    private function compile(string $infraFixture = IacKafkaInfraFixture::class): array
    {
        $container = new ContainerBuilder();
        $container->register(IacKafkaMessagingFixture::class, IacKafkaMessagingFixture::class)
            ->addTag('vortos.messaging_config');
        $container->register($infraFixture, $infraFixture)
            ->addTag('vortos.infra_config');

        (new MessagingConfigCompilerPass())->process($container);
        (new InfraConfigCompilerPass())->process($container);

        // Same unescape parameter resolution performs on compile.
        return $container->getParameterBag()->resolveValue($container->getParameter('vortos.iac.exports'));
    }

    private function exporter(): KafkaTopicsExporter
    {
        return new KafkaTopicsExporter([new ConfluentTopicMapper(), new MongeyKafkaTopicMapper()]);
    }

    public function test_compiled_entry_shape(): void
    {
        $exports = $this->compile();

        $this->assertCount(1, $exports);
        $entry = $exports[0];

        $this->assertSame('kafka-topics', $entry['name']);
        $this->assertSame(KafkaTopicsExporter::class, $entry['exporter']);
        $this->assertSame('infra/kafka_topics.tf.json', $entry['output_file']);
        $this->assertSame('infra/kafka_topics_variables.tf.json', $entry['variables_file']);

        $topics = $entry['spec']['topics'];
        $this->assertCount(1, $topics, 'debug.* must be excluded');
        $this->assertSame('orders_placed', $topics[0]['label']);
        $this->assertSame('orders.placed', $topics[0]['name']);
    }

    public function test_confluent_golden_output(): void
    {
        $entry = $this->compile()[0];
        $document = $this->exporter()->export($entry);

        $expected = <<<'JSON'
{
    "//": "GENERATED by vortos:iac:export — do not edit; change your InfraConfig and re-export.",
    "terraform": {
        "required_providers": {
            "confluent": {
                "source": "confluentinc/confluent",
                "version": "~> 2.0"
            }
        }
    },
    "resource": {
        "confluent_kafka_topic": {
            "orders_placed": {
                "config": {
                    "cleanup.policy": "delete",
                    "retention.ms": "${var.kafka_retention_ms}"
                },
                "kafka_cluster": {
                    "id": "${confluent_kafka_cluster.main.id}"
                },
                "partitions_count": "${var.kafka_partitions}",
                "topic_name": "orders.placed"
            }
        }
    }
}

JSON;
        $this->assertSame($expected, $document->render(includeVariables: false));

        $variables = json_decode($document->variablesDocument()->render(), true);
        $this->assertSame(
            ['default' => 12, 'description' => 'From environment variable KAFKA_PARTITIONS.', 'type' => 'number'],
            $variables['variable']['kafka_partitions'],
        );
        $this->assertSame(
            ['default' => 604800000, 'description' => 'From environment variable KAFKA_RETENTION_MS.', 'type' => 'number'],
            $variables['variable']['kafka_retention_ms'],
        );
    }

    public function test_mongey_output_includes_replication(): void
    {
        $entry = $this->compile()[0];
        $entry['spec']['provider'] = KafkaProvider::Kafka->value;
        $entry['spec']['cluster_ref'] = null;

        $decoded = json_decode($this->exporter()->export($entry)->render(includeVariables: false), true);
        $topic = $decoded['resource']['kafka_topic']['orders_placed'];

        $this->assertSame('orders.placed', $topic['name']);
        $this->assertSame(3, $topic['replication_factor']);
        $this->assertSame('${var.kafka_partitions}', $topic['partitions']);
        $this->assertSame('Mongey/kafka', $decoded['terraform']['required_providers']['kafka']['source']);
    }

    public function test_sasl_credentials_never_reach_the_export(): void
    {
        $entry = $this->compile()[0];
        $document = $this->exporter()->export($entry);
        $everything = $document->render(includeVariables: false) . $document->variablesDocument()->render();

        $this->assertStringNotContainsString('sasl', strtolower($everything));
        $this->assertStringNotContainsString('ssl', strtolower($everything));
        $this->assertStringNotContainsString('dsn', strtolower($everything));
        $this->assertStringNotContainsString('kafka_brokers', strtolower($everything), 'Connection DSN is client auth, not topic infra');
    }

    public function test_resource_count(): void
    {
        $this->assertSame(1, $this->exporter()->countResources($this->compile()[0]));
    }
}
