<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\DependencyInjection\Exception\LogicException;
use Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;
use Symfony\Component\DependencyInjection\ParameterBag\FrozenParameterBag;
use Symfony\Component\DependencyInjection\ParameterBag\ParameterBagInterface;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class CachedContainer extends Container
{
    protected $parameters = [];

    public function __construct()
    {
        $this->parameters = $this->getDefaultParameters();

        $this->services = $this->privates = [];
        $this->syntheticIds = [
            'Symfony\\Component\\Routing\\RouteCollection' => true,
        ];
        $this->methodMap = [
            'App\\User\\Representation\\Controller\\CreateAnEventController' => 'getCreateAnEventControllerService',
            'App\\User\\Representation\\Controller\\GetUserController' => 'getGetUserControllerService',
            'App\\User\\Representation\\Controller\\TestDoctrineController' => 'getTestDoctrineControllerService',
            'App\\User\\Representation\\Controller\\TestMongoController' => 'getTestMongoControllerService',
            'App\\User\\Representation\\Controller\\UserRegisterController' => 'getUserRegisterControllerService',
            'Fortizan\\Tekton\\Controller\\ErrorController' => 'getErrorControllerService',
            'Fortizan\\Tekton\\EventListener\\ContentLengthListener' => 'getContentLengthListenerService',
            'Fortizan\\Tekton\\EventListener\\GoogleListener' => 'getGoogleListenerService',
            'Fortizan\\Tekton\\EventListener\\StringResponseListener' => 'getStringResponseListenerService',
            'tekton' => 'getTektonService',
        ];

        $this->aliases = [];
    }

    public function compile(): void
    {
        throw new LogicException('You cannot compile a dumped container that was already compiled.');
    }

    public function isCompiled(): bool
    {
        return true;
    }

    public function getRemovedIds(): array
    {
        return [
            'App\\Shared\\Infrastructure\\Database\\Migrations\\Version20251228051847' => true,
            'App\\User\\Application\\Command\\RegisterUser\\RegisterUserCommand' => true,
            'App\\User\\Application\\Command\\RegisterUser\\RegisterUserCommandHandler' => true,
            'App\\User\\Application\\Projection\\UserProjector' => true,
            'App\\User\\Application\\Query\\GetUser\\GetUserQuery' => true,
            'App\\User\\Application\\Query\\GetUser\\GetUserQueryHandler' => true,
            'App\\User\\Application\\Query\\GetUser\\GetUserResponse' => true,
            'App\\User\\Domain\\Entity\\User' => true,
            'App\\User\\Domain\\Event\\UserCreatedEvent' => true,
            'App\\User\\Domain\\Exception\\UserNotFoundException' => true,
            'App\\User\\Domain\\Repository\\UserRepositoryInterface' => true,
            'App\\User\\Infrastructure\\Query\\DbalUserFinder' => true,
            'App\\User\\Infrastructure\\Query\\MongoUserFinder' => true,
            'App\\User\\Infrastructure\\Repository\\DoctrineUserRepository' => true,
            'App\\User\\Representation\\View' => true,
            'App\\test' => true,
            'Fortizan\\Tekton\\Attribute\\ApiController' => true,
            'Fortizan\\Tekton\\Bus\\Command\\Attribute\\CommandHandler' => true,
            'Fortizan\\Tekton\\Bus\\Command\\CommandBus' => true,
            'Fortizan\\Tekton\\Bus\\Query\\Attribute\\QueryHandler' => true,
            'Fortizan\\Tekton\\Bus\\Query\\QueryBus' => true,
            'Fortizan\\Tekton\\Container\\Container' => true,
            'Fortizan\\Tekton\\DependencyInjection\\Compiler\\Cqrs\\CommandHandlerPass' => true,
            'Fortizan\\Tekton\\DependencyInjection\\Compiler\\Cqrs\\QueryHandlerPass' => true,
            'Fortizan\\Tekton\\DependencyInjection\\Compiler\\Http\\RegisterEventSubscribersPass' => true,
            'Fortizan\\Tekton\\DependencyInjection\\TektonExtension' => true,
            'Fortizan\\Tekton\\EventListener' => true,
            'Fortizan\\Tekton\\Http\\Event\\ResponseEvent' => true,
            'Fortizan\\Tekton\\Http\\Event\\TestEvent' => true,
            'Fortizan\\Tekton\\Http\\Kernel' => true,
            'Fortizan\\Tekton\\Infrastructure\\Doctrine\\DomainEventDispatcher' => true,
            'Fortizan\\Tekton\\Persistence\\Adapter\\DoctrineSourceReader' => true,
            'Fortizan\\Tekton\\Persistence\\Adapter\\DoctrineSourceWriter' => true,
            'Fortizan\\Tekton\\Persistence\\Adapter\\MongoProjectionReader' => true,
            'Fortizan\\Tekton\\Persistence\\Adapter\\MongoProjectionWriter' => true,
            'Fortizan\\Tekton\\Persistence\\Contract\\PersistenceFactoryInterface' => true,
            'Fortizan\\Tekton\\Persistence\\Contract\\PersistenceManagerInterface' => true,
            'Fortizan\\Tekton\\Persistence\\Contract\\ProjectionReaderInterface' => true,
            'Fortizan\\Tekton\\Persistence\\Contract\\ProjectionWriterInterface' => true,
            'Fortizan\\Tekton\\Persistence\\Contract\\SourceReaderInterface' => true,
            'Fortizan\\Tekton\\Persistence\\Contract\\SourceWriterInterface' => true,
            'Fortizan\\Tekton\\Persistence\\CustomType\\Uuid' => true,
            'Fortizan\\Tekton\\Persistence\\PersistenceFactory' => true,
            'Fortizan\\Tekton\\Persistence\\PersistenceManager' => true,
            'Fortizan\\Tekton\\Routing\\RouteAttributeClassLoader' => true,
            'Psr\\Log\\LoggerInterface' => true,
            'Symfony\\Component\\EventDispatcher\\EventDispatcher' => true,
            'Symfony\\Component\\HttpFoundation\\RequestStack' => true,
            'Symfony\\Component\\HttpKernel\\Controller\\ArgumentResolver' => true,
            'Symfony\\Component\\HttpKernel\\Controller\\ContainerControllerResolver' => true,
            'Symfony\\Component\\HttpKernel\\EventListener\\ErrorListener' => true,
            'Symfony\\Component\\HttpKernel\\EventListener\\ResponseListener' => true,
            'Symfony\\Component\\HttpKernel\\EventListener\\RouterListener' => true,
            'Symfony\\Component\\Messenger\\MessageBusInterface' => true,
            'Symfony\\Component\\Messenger\\MessageBusInterface $commandBus' => true,
            'Symfony\\Component\\Messenger\\MessageBusInterface $messageBus' => true,
            'Symfony\\Component\\Messenger\\MessageBusInterface $queryBus' => true,
            'Symfony\\Component\\Routing\\Matcher\\UrlMatcher' => true,
            'Symfony\\Component\\Routing\\RequestContext' => true,
            'messenger.bus.default' => true,
            'messenger.bus.default.messenger.handlers_locator' => true,
            'messenger.middleware.handle_message' => true,
            'monolog.formatter.json' => true,
            'monolog.formatter.line' => true,
            'monolog.handler.main' => true,
            'monolog.logger' => true,
            'monolog.processor.introspection' => true,
            'tekton.bus.command' => true,
            'tekton.bus.command.locator' => true,
            'tekton.bus.command.messenger.handlers_locator' => true,
            'tekton.bus.command.middleware' => true,
            'tekton.bus.query' => true,
            'tekton.bus.query.locator' => true,
            'tekton.bus.query.messenger.handlers_locator' => true,
            'tekton.bus.query.middleware' => true,
        ];
    }

    /**
     * Gets the public 'App\User\Representation\Controller\CreateAnEventController' shared autowired service.
     *
     * @return \App\User\Representation\Controller\CreateAnEventController
     */
    protected static function getCreateAnEventControllerService($container)
    {
        return $container->services['App\\User\\Representation\\Controller\\CreateAnEventController'] = new \App\User\Representation\Controller\CreateAnEventController(($container->privates['Symfony\\Component\\EventDispatcher\\EventDispatcher'] ?? self::getEventDispatcherService($container)));
    }

    /**
     * Gets the public 'App\User\Representation\Controller\GetUserController' shared autowired service.
     *
     * @return \App\User\Representation\Controller\GetUserController
     */
    protected static function getGetUserControllerService($container)
    {
        return $container->services['App\\User\\Representation\\Controller\\GetUserController'] = new \App\User\Representation\Controller\GetUserController(new \Fortizan\Tekton\Bus\Query\QueryBus(new \Symfony\Component\Messenger\MessageBus([new \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware(new \Symfony\Component\Messenger\Handler\HandlersLocator(['App\\User\\Application\\Query\\GetUser\\GetUserQuery' => [new \App\User\Application\Query\GetUser\GetUserQueryHandler()]]))])));
    }

    /**
     * Gets the public 'App\User\Representation\Controller\TestDoctrineController' shared autowired service.
     *
     * @return \App\User\Representation\Controller\TestDoctrineController
     */
    protected static function getTestDoctrineControllerService($container)
    {
        $a = ($container->privates['Fortizan\\Tekton\\Persistence\\PersistenceManager'] ?? self::getPersistenceManagerService($container));

        return $container->services['App\\User\\Representation\\Controller\\TestDoctrineController'] = new \App\User\Representation\Controller\TestDoctrineController(new \App\User\Infrastructure\Repository\DoctrineUserRepository($a), new \App\User\Infrastructure\Query\DbalUserFinder($a));
    }

    /**
     * Gets the public 'App\User\Representation\Controller\TestMongoController' shared autowired service.
     *
     * @return \App\User\Representation\Controller\TestMongoController
     */
    protected static function getTestMongoControllerService($container)
    {
        return $container->services['App\\User\\Representation\\Controller\\TestMongoController'] = new \App\User\Representation\Controller\TestMongoController(($container->privates['Fortizan\\Tekton\\Persistence\\PersistenceManager'] ?? self::getPersistenceManagerService($container)));
    }

    /**
     * Gets the public 'App\User\Representation\Controller\UserRegisterController' shared autowired service.
     *
     * @return \App\User\Representation\Controller\UserRegisterController
     */
    protected static function getUserRegisterControllerService($container)
    {
        return $container->services['App\\User\\Representation\\Controller\\UserRegisterController'] = new \App\User\Representation\Controller\UserRegisterController(new \Fortizan\Tekton\Bus\Command\CommandBus(new \Symfony\Component\Messenger\MessageBus([new \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware(new \Symfony\Component\Messenger\Handler\HandlersLocator(['App\\User\\Application\\Command\\RegisterUser\\RegisterUserCommand' => [new \App\User\Application\Command\RegisterUser\RegisterUserCommandHandler()]]))])));
    }

    /**
     * Gets the public 'Fortizan\Tekton\Controller\ErrorController' shared autowired service.
     *
     * @return \Fortizan\Tekton\Controller\ErrorController
     */
    protected static function getErrorControllerService($container)
    {
        return $container->services['Fortizan\\Tekton\\Controller\\ErrorController'] = new \Fortizan\Tekton\Controller\ErrorController(true, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }

    /**
     * Gets the public 'Fortizan\Tekton\EventListener\ContentLengthListener' shared autowired service.
     *
     * @return \Fortizan\Tekton\EventListener\ContentLengthListener
     */
    protected static function getContentLengthListenerService($container)
    {
        return $container->services['Fortizan\\Tekton\\EventListener\\ContentLengthListener'] = new \Fortizan\Tekton\EventListener\ContentLengthListener();
    }

    /**
     * Gets the public 'Fortizan\Tekton\EventListener\GoogleListener' shared autowired service.
     *
     * @return \Fortizan\Tekton\EventListener\GoogleListener
     */
    protected static function getGoogleListenerService($container)
    {
        return $container->services['Fortizan\\Tekton\\EventListener\\GoogleListener'] = new \Fortizan\Tekton\EventListener\GoogleListener();
    }

    /**
     * Gets the public 'Fortizan\Tekton\EventListener\StringResponseListener' shared autowired service.
     *
     * @return \Fortizan\Tekton\EventListener\StringResponseListener
     */
    protected static function getStringResponseListenerService($container)
    {
        return $container->services['Fortizan\\Tekton\\EventListener\\StringResponseListener'] = new \Fortizan\Tekton\EventListener\StringResponseListener();
    }

    /**
     * Gets the public 'tekton' shared autowired service.
     *
     * @return \Fortizan\Tekton\Http\Kernel
     */
    protected static function getTektonService($container)
    {
        return $container->services['tekton'] = new \Fortizan\Tekton\Http\Kernel(($container->privates['Symfony\\Component\\EventDispatcher\\EventDispatcher'] ?? self::getEventDispatcherService($container)), new \Symfony\Component\HttpKernel\Controller\ContainerControllerResolver($container, ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container))), ($container->privates['Symfony\\Component\\HttpFoundation\\RequestStack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), new \Symfony\Component\HttpKernel\Controller\ArgumentResolver());
    }

    /**
     * Gets the private '.messenger.handler_descriptor.xbJUMGL' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    protected static function get_Messenger_HandlerDescriptor_XbJUMGLService($container)
    {
        return $container->privates['.messenger.handler_descriptor.xbJUMGL'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor((new \App\User\Application\Projection\UserProjector(($container->privates['Fortizan\\Tekton\\Persistence\\PersistenceFactory'] ??= new \Fortizan\Tekton\Persistence\PersistenceFactory('/var/www/html/packages/Tekton/src/Container/../../../..'))->createProjectionWriter([])))->handle(...), ['method' => 'handle']);
    }

    /**
     * Gets the private 'Fortizan\Tekton\Persistence\PersistenceManager' shared autowired service.
     *
     * @return \Fortizan\Tekton\Persistence\PersistenceManager
     */
    protected static function getPersistenceManagerService($container)
    {
        $a = ($container->privates['Fortizan\\Tekton\\Persistence\\PersistenceFactory'] ??= new \Fortizan\Tekton\Persistence\PersistenceFactory('/var/www/html/packages/Tekton/src/Container/../../../..'));

        return $container->privates['Fortizan\\Tekton\\Persistence\\PersistenceManager'] = new \Fortizan\Tekton\Persistence\PersistenceManager($a->createSourceWriter(new \Symfony\Component\Messenger\MessageBus([new \Symfony\Component\Messenger\Middleware\HandleMessageMiddleware(new \Symfony\Component\Messenger\Handler\HandlersLocator(['App\\User\\Domain\\Event\\UserCreatedEvent' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['.messenger.handler_descriptor.xbJUMGL'] ?? self::get_Messenger_HandlerDescriptor_XbJUMGLService($container));
        }, 1)]))]), [], [], true), $a->createSourceReader([], true), $a->createProjectionReader([]));
    }

    /**
     * Gets the private 'Symfony\Component\EventDispatcher\EventDispatcher' shared autowired service.
     *
     * @return \Symfony\Component\EventDispatcher\EventDispatcher
     */
    protected static function getEventDispatcherService($container)
    {
        $container->privates['Symfony\\Component\\EventDispatcher\\EventDispatcher'] = $instance = new \Symfony\Component\EventDispatcher\EventDispatcher();

        $a = new \Symfony\Component\Routing\RequestContext();
        $b = ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container));

        $instance->addSubscriber(new \Symfony\Component\HttpKernel\EventListener\RouterListener(new \Symfony\Component\Routing\Matcher\UrlMatcher(($container->services['Symfony\\Component\\Routing\\RouteCollection'] ?? $container->get('Symfony\\Component\\Routing\\RouteCollection', 1)), $a), ($container->privates['Symfony\\Component\\HttpFoundation\\RequestStack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()), $a, $b));
        $instance->addSubscriber(new \Symfony\Component\HttpKernel\EventListener\ResponseListener('UTF-8'));
        $instance->addSubscriber(new \Symfony\Component\HttpKernel\EventListener\ErrorListener('Fortizan\\Tekton\\Controller\\ErrorController', $b));
        $instance->addSubscriber(($container->services['Fortizan\\Tekton\\EventListener\\ContentLengthListener'] ??= new \Fortizan\Tekton\EventListener\ContentLengthListener()));
        $instance->addSubscriber(($container->services['Fortizan\\Tekton\\EventListener\\GoogleListener'] ??= new \Fortizan\Tekton\EventListener\GoogleListener()));
        $instance->addSubscriber(($container->services['Fortizan\\Tekton\\EventListener\\StringResponseListener'] ??= new \Fortizan\Tekton\EventListener\StringResponseListener()));

        return $instance;
    }

    /**
     * Gets the private 'monolog.logger' shared service.
     *
     * @return \Monolog\Logger
     */
    protected static function getMonolog_LoggerService($container)
    {
        $container->privates['monolog.logger'] = $instance = new \Monolog\Logger('app');

        $a = new \Monolog\Handler\StreamHandler('/var/www/html/packages/Tekton/src/Container/../../../../var/log/dev.log', \Monolog\Level::Debug);
        $a->setFormatter(new \Monolog\Formatter\LineFormatter());

        $instance->pushHandler($a);
        $instance->pushProcessor(new \Monolog\Processor\IntrospectionProcessor());

        return $instance;
    }

    public function getParameter(string $name): array|bool|string|int|float|\UnitEnum|null
    {
        if (!(isset($this->parameters[$name]) || isset($this->loadedDynamicParameters[$name]) || \array_key_exists($name, $this->parameters))) {
            throw new ParameterNotFoundException($name);
        }

        if (isset($this->loadedDynamicParameters[$name])) {
            $value = $this->loadedDynamicParameters[$name] ? $this->dynamicParameters[$name] : $this->getDynamicParameter($name);
        } else {
            $value = $this->parameters[$name];
        }

        return $value;
    }

    public function hasParameter(string $name): bool
    {
        return isset($this->parameters[$name]) || isset($this->loadedDynamicParameters[$name]) || \array_key_exists($name, $this->parameters);
    }

    public function setParameter(string $name, $value): void
    {
        throw new LogicException('Impossible to call set() on a frozen ParameterBag.');
    }

    public function getParameterBag(): ParameterBagInterface
    {
        if (!isset($this->parameterBag)) {
            $parameters = $this->parameters;
            foreach ($this->loadedDynamicParameters as $name => $loaded) {
                $parameters[$name] = $loaded ? $this->dynamicParameters[$name] : $this->getDynamicParameter($name);
            }
            $this->parameterBag = new FrozenParameterBag($parameters, []);
        }

        return $this->parameterBag;
    }

    private $loadedDynamicParameters = [];
    private $dynamicParameters = [];

    private function getDynamicParameter(string $name)
    {
        throw new ParameterNotFoundException($name);
    }

    protected function getDefaultParameters(): array
    {
        return [
            'kernel.project_dir' => '/var/www/html/packages/Tekton/src/Container/../../../..',
            'charset' => 'UTF-8',
            'kernel.log_path' => '/var/www/html/packages/Tekton/src/Container/../../../../var/log',
            'kernel.env' => 'dev',
            'kernel.debug' => true,
        ];
    }
}
