<?php
declare(strict_types=1);
namespace Vortos\Auth\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;
use Vortos\Auth\Audit\AuditFailureMode;
use Vortos\Auth\Lockout\LockoutFailureMode;
use Vortos\Auth\Quota\QuotaFailureMode;
use Vortos\Auth\RateLimit\RateLimitFailureMode;
use Vortos\Auth\Storage\InMemoryTokenStorage;

final class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('vortos_auth');

        $treeBuilder->getRootNode()
            ->children()
                ->integerNode('access_token_ttl')
                    ->defaultValue(900)
                    ->info('Access token TTL in seconds. Default: 900 (15 minutes)')
                ->end()
                ->integerNode('refresh_token_ttl')
                    ->defaultValue(604800)
                    ->info('Refresh token TTL in seconds. Default: 604800 (7 days)')
                ->end()
                ->booleanNode('enforce_session_liveness')
                    ->defaultFalse()
                    ->info('When true, every authenticated request checks that the access token\'s session (sid claim) is still a live session in the session store, returning 401 if it was revoked. Turns access-token revocation from "effective at next refresh" (up to access_token_ttl later) into "effective within session_liveness_cache_ttl_seconds". Requires Redis + a SessionPolicy (so sessions are tracked). Cached + circuit-broken (see below); fails open on store errors. Default: false (stateless access tokens).')
                ->end()
                ->integerNode('session_liveness_cache_ttl_seconds')
                    ->defaultValue(5)
                    ->min(0)
                    ->info('Positive-cache window (seconds) for session-liveness. A "still live" answer is cached in-process for this long, so a busy session costs at most one store lookup per window instead of one per request. Only live answers are cached — a revoked session is returned immediately — so this is also the upper bound on revocation latency. 0 disables the cache (strict per-request check). Default: 5.')
                ->end()
                ->integerNode('session_liveness_circuit_breaker_threshold')
                    ->defaultValue(5)
                    ->min(1)
                    ->info('Consecutive session-store failures before the liveness circuit breaker opens (after which it fails open without touching the store until the reset window elapses). Default: 5.')
                ->end()
                ->integerNode('session_liveness_circuit_breaker_reset_seconds')
                    ->defaultValue(30)
                    ->min(1)
                    ->info('Seconds before the liveness circuit breaker transitions from open to half-open (allowing one probe). Default: 30.')
                ->end()
                ->integerNode('refresh_rotation_grace_seconds')
                    ->defaultValue(0)
                    ->min(0)
                    ->info('Grace window (seconds) during which a just-rotated refresh token may be presented again without triggering reuse/theft detection. Absorbs benign races (concurrent tabs, retried refresh requests over flaky networks) instead of revoking all sessions. 0 (default) = strict one-time-use, no grace. Keep small (e.g. 30).')
                ->end()
                ->scalarNode('issuer')
                    ->defaultValue('vortos')
                    ->info('JWT issuer claim — use your app/org name or domain')
                ->end()
                ->scalarNode('audience')
                    ->defaultValue('vortos')
                    ->info('JWT audience claim — identifies the intended recipient service. Prevents cross-service token confusion.')
                ->end()
                ->scalarNode('token_storage')
                    ->defaultValue(InMemoryTokenStorage::class)
                    ->info('FQCN of TokenStorageInterface implementation')
                ->end()
                ->enumNode('lockout_failure_mode')
                    ->values([LockoutFailureMode::FailClosed->value, LockoutFailureMode::FailOpen->value])
                    ->defaultValue(LockoutFailureMode::FailClosed->value)
                    ->info('Lockout behavior when Redis is unavailable. FailClosed denies login (safe default).')
                ->end()
                ->integerNode('lockout_circuit_breaker_threshold')
                    ->defaultValue(3)
                    ->min(1)
                    ->info('Consecutive Redis failures before the lockout circuit breaker opens.')
                ->end()
                ->integerNode('lockout_circuit_breaker_reset_seconds')
                    ->defaultValue(30)
                    ->min(1)
                    ->info('Seconds before the lockout circuit breaker transitions from open to half-open.')
                ->end()
                ->enumNode('quota_failure_mode')
                    ->values([QuotaFailureMode::FailClosed->value, QuotaFailureMode::FailOpen->value])
                    ->defaultValue(QuotaFailureMode::FailClosed->value)
                    ->info('Quota behavior when Redis is unavailable.')
                ->end()
                ->booleanNode('quota_headers')
                    ->defaultTrue()
                    ->info('Emit X-Quota-* headers on quota-protected responses.')
                ->end()
                ->booleanNode('quota_compensate_on_server_error')
                    ->defaultTrue()
                    ->info('Refund consumed quota when the downstream handler returns a 5xx response. Prevents griefing via server errors.')
                ->end()
                ->booleanNode('rate_limit_headers')
                    ->defaultTrue()
                    ->info('Emit X-RateLimit-* headers on rate-limited responses.')
                ->end()
                ->enumNode('rate_limit_failure_mode_ip')
                    ->values([RateLimitFailureMode::FailClosed->value, RateLimitFailureMode::FailOpen->value])
                    ->defaultValue(RateLimitFailureMode::FailClosed->value)
                    ->info('Rate limit behavior when Redis is unavailable for IP-scoped limits.')
                ->end()
                ->enumNode('rate_limit_failure_mode_global')
                    ->values([RateLimitFailureMode::FailClosed->value, RateLimitFailureMode::FailOpen->value])
                    ->defaultValue(RateLimitFailureMode::FailClosed->value)
                    ->info('Rate limit behavior when Redis is unavailable for Global-scoped limits.')
                ->end()
                ->enumNode('rate_limit_failure_mode_user')
                    ->values([RateLimitFailureMode::FailClosed->value, RateLimitFailureMode::FailOpen->value])
                    ->defaultValue(RateLimitFailureMode::FailOpen->value)
                    ->info('Rate limit behavior when Redis is unavailable for User-scoped limits.')
                ->end()
                ->integerNode('rate_limit_circuit_breaker_threshold')
                    ->defaultValue(5)
                    ->min(1)
                    ->info('Consecutive Redis failures before the circuit breaker opens.')
                ->end()
                ->integerNode('rate_limit_circuit_breaker_reset_seconds')
                    ->defaultValue(30)
                    ->min(1)
                    ->info('Seconds before the circuit breaker transitions from open to half-open.')
                ->end()
                ->booleanNode('problem_details')
                    ->defaultTrue()
                    ->info('Emit RFC 7807-style application/problem+json responses for auth policy failures.')
                ->end()
                ->enumNode('audit_failure_mode')
                    ->values([AuditFailureMode::FailClosed->value, AuditFailureMode::FailOpen->value])
                    ->defaultValue(AuditFailureMode::FailClosed->value)
                    ->info('Audit behavior when the audit store is unavailable or fails. FailClosed returns 503 (safe default for security events).')
                ->end()
                ->scalarNode('audit_hmac_key')
                    ->defaultValue('')
                    ->info('HMAC-SHA256 key for audit chain integrity. When set, audit entries are hash-chained and signed. Generate: bin2hex(random_bytes(32)).')
                ->end()
                ->integerNode('api_key_max_inactivity_seconds')
                    ->defaultValue(-1)
                    ->info('Maximum seconds an API key can go unused before it is rejected. -1 disables. Recommended: 7776000 (90 days).')
                ->end()
                ->scalarNode('tenant_claim')
                    ->defaultValue('tenant')
                    ->info('JWT claim carrying the tenant id, used to populate TenantContext.')
                ->end()
            ->end();

        return $treeBuilder;
    }
}
