<?php

declare(strict_types=1);

namespace Vortos\Iac\Export;

use Vortos\Iac\Exception\PathViolationException;
use Vortos\Iac\Terraform\TerraformDocument;

/**
 * The only component that touches the filesystem.
 *
 * Rules:
 *  - paths re-validated and resolved through PathPolicy (project-dir jail,
 *    symlink re-check) even though the compiler pass validated them already;
 *  - refuses to overwrite an existing file that lacks the generated-file
 *    marker — hand-written Terraform can never be clobbered, and there is
 *    deliberately no --force;
 *  - writes are atomic (temp file + rename in the same directory), 0644.
 */
final class SafeFileWriter
{
    public function __construct(private readonly string $projectDir) {}

    public function write(string $relativePath, string $content): FileOutcome
    {
        $target = PathPolicy::resolveInside($this->projectDir, $relativePath);

        if (file_exists($target)) {
            $this->assertGenerated($target, $relativePath);

            if (file_get_contents($target) === $content) {
                return FileOutcome::Unchanged;
            }
        }

        $temp = $target . '.' . bin2hex(random_bytes(6)) . '.tmp';

        try {
            if (file_put_contents($temp, $content) !== strlen($content)) {
                throw new PathViolationException(sprintf("Failed writing '%s'.", $relativePath));
            }

            chmod($temp, 0644);

            if (!rename($temp, $target)) {
                throw new PathViolationException(sprintf("Failed moving '%s' into place.", $relativePath));
            }
        } finally {
            if (file_exists($temp)) {
                @unlink($temp);
            }
        }

        return FileOutcome::Written;
    }

    /** Byte-exact drift check; never writes. */
    public function check(string $relativePath, string $content): FileOutcome
    {
        $target = PathPolicy::resolveInside($this->projectDir, $relativePath);

        if (!file_exists($target) || file_get_contents($target) !== $content) {
            return FileOutcome::Drift;
        }

        return FileOutcome::Unchanged;
    }

    private function assertGenerated(string $target, string $relativePath): void
    {
        $head = (string) file_get_contents($target, length: 512);

        if (!str_contains($head, TerraformDocument::GENERATED_MARKER)) {
            throw new PathViolationException(sprintf(
                "Refusing to overwrite '%s': it exists but was not generated by vortos:iac:export. "
                . 'Rename your file or choose a different outputFile().',
                $relativePath,
            ));
        }
    }
}
