<?php

declare(strict_types=1);

namespace Vortos\Ses\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

/**
 * Validates the vortos_ses configuration tree.
 *
 * All nodes have defaults — no config file is required.
 * Root node alias must match SesExtension::getAlias(): 'vortos_ses'
 */
final class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('vortos_ses');

        $treeBuilder->getRootNode()
            ->addDefaultsIfNotSet()
            ->children()

                ->scalarNode('driver')
                    ->defaultValue('log')
                    ->info('Mailer driver: ses | log | null')
                ->end()

                ->scalarNode('region')
                    ->defaultValue('us-east-1')
                    ->info('Primary AWS SES region')
                ->end()

                ->scalarNode('fallback_region')
                    ->defaultNull()
                    ->info('Fallback AWS SES region for multi-region failover. Null disables failover.')
                ->end()

                ->scalarNode('default_from_address')
                    ->defaultValue('')
                    ->info('Default sender email address used when Email::from is not set.')
                ->end()

                ->scalarNode('default_from_name')
                    ->defaultValue('')
                    ->info('Default sender display name.')
                ->end()

                ->scalarNode('reply_to')
                    ->defaultNull()
                    ->info('Default Reply-To address applied to all outgoing email.')
                ->end()

                ->scalarNode('configuration_set')
                    ->defaultNull()
                    ->info('AWS SES configuration set name for open/click/bounce tracking.')
                ->end()

                ->scalarNode('template_dir')
                    ->defaultNull()
                    ->info('Directory containing PHP email templates (*.html.php, *.text.php). Null uses NullTemplateRenderer.')
                ->end()

                ->arrayNode('aws_client')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('endpoint_override')
                            ->defaultNull()
                            ->info('Override AWS endpoint URL. Used for LocalStack: http://localstack:4566')
                        ->end()
                        ->floatNode('http_timeout')
                            ->defaultValue(2.0)
                            ->info('HTTP timeout in seconds for SES API calls.')
                        ->end()
                        ->integerNode('max_retries')
                            ->defaultValue(3)
                            ->info('AWS SDK retry count for transient errors.')
                        ->end()
                    ->end()
                ->end()

                ->arrayNode('outbox')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultTrue()
                            ->info('Enable the SES transactional outbox. Disable only for synchronous send (no relay worker).')
                        ->end()
                        ->scalarNode('table_name')
                            ->defaultValue('ses_outbox')
                            ->info('DB table used to store pending outbox emails.')
                        ->end()
                        ->integerNode('batch_size')
                            ->defaultValue(50)
                            ->info('Number of outbox rows fetched per relay worker iteration.')
                        ->end()
                        ->integerNode('sleep_seconds_when_empty')
                            ->defaultValue(2)
                            ->info('Seconds the relay worker sleeps when the outbox is empty.')
                        ->end()
                        ->integerNode('max_delivery_attempts')
                            ->defaultValue(5)
                            ->info('Maximum delivery attempts before an outbox row is permanently failed.')
                        ->end()
                        ->scalarNode('retry_strategy')
                            ->defaultValue('exponential')
                            ->info('Retry backoff strategy: exponential | linear | fixed')
                        ->end()
                        ->integerNode('backoff_base_seconds')
                            ->defaultValue(30)
                            ->info('Initial retry delay in seconds. Doubles on each attempt (exponential).')
                        ->end()
                        ->integerNode('backoff_cap_seconds')
                            ->defaultValue(3600)
                            ->info('Maximum retry delay in seconds.')
                        ->end()
                        ->integerNode('stale_message_timeout_seconds')
                            ->defaultValue(300)
                            ->info('Seconds before a stuck "processing" outbox row is reset to pending.')
                        ->end()
                    ->end()
                ->end()

                ->arrayNode('webhooks')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultTrue()
                            ->info('Register the SNS webhook controller for bounce/complaint notifications.')
                        ->end()
                        ->scalarNode('route_path')
                            ->defaultValue('/webhooks/aws/ses')
                            ->info('HTTP path for the SNS webhook endpoint.')
                        ->end()
                    ->end()
                ->end()

                ->arrayNode('suppression')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('table_name')
                            ->defaultValue('ses_suppression_list')
                            ->info('DB table used to store locally suppressed addresses.')
                        ->end()
                        ->booleanNode('sync_on_startup')
                            ->defaultFalse()
                            ->info('Sync AWS account-level suppression list to local DB on container boot.')
                        ->end()
                        ->scalarNode('on_suppressed')
                            ->defaultValue('throw')
                            ->info('Behaviour when a suppressed recipient is found: throw | strip')
                        ->end()
                    ->end()
                ->end()

                ->arrayNode('rate_limit')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->integerNode('max_send_rate')
                            ->defaultValue(14)
                            ->info('Maximum emails per second. Match your SES account sending rate.')
                        ->end()
                        ->integerNode('burst')
                            ->defaultValue(14)
                            ->info('Token bucket burst capacity.')
                        ->end()
                        ->integerNode('wait_timeout_ms')
                            ->defaultValue(5000)
                            ->info('Milliseconds to wait for a rate-limit token before throwing.')
                        ->end()
                    ->end()
                ->end()

                ->arrayNode('audit_log')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultTrue()
                            ->info('Record every send attempt in the ses_audit_log table.')
                        ->end()
                        ->scalarNode('table_name')
                            ->defaultValue('ses_audit_log')
                            ->info('DB table used for the send audit trail.')
                        ->end()
                    ->end()
                ->end()

                ->arrayNode('circuit_breaker')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->integerNode('failure_threshold')
                            ->defaultValue(5)
                            ->info('Consecutive failures before the circuit opens.')
                        ->end()
                        ->integerNode('reset_timeout_seconds')
                            ->defaultValue(60)
                            ->info('Seconds the circuit stays open before allowing a probe request.')
                        ->end()
                    ->end()
                ->end()

                ->arrayNode('rate_limit')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->integerNode('max_send_rate')
                            ->defaultValue(14)
                            ->info('Maximum emails per second. Match your SES account sending rate.')
                        ->end()
                        ->integerNode('burst')
                            ->defaultValue(14)
                            ->info('Token bucket burst capacity.')
                        ->end()
                        ->integerNode('wait_timeout_ms')
                            ->defaultValue(5000)
                            ->info('Milliseconds to wait for a token before throwing RateLimitExceededException.')
                        ->end()
                    ->end()
                ->end()

                ->arrayNode('audit_log')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->booleanNode('enabled')
                            ->defaultTrue()
                            ->info('Record every send attempt in the ses_audit_log table.')
                        ->end()
                        ->scalarNode('table_name')
                            ->defaultValue('ses_audit_log')
                            ->info('DB table used for the send audit trail.')
                        ->end()
                    ->end()
                ->end()

            ->end();

        return $treeBuilder;
    }
}
