[supervisord]
nodaemon=true
user=root

[program:worker_async]
command=php /var/www/html/bin/consume async
autostart=true
autorestart=true
stderr_logfile=/var/log/worker_async.err.log
stdout_logfile=/var/log/worker_async.out.log

# Users can add more blocks here for their specific Group IDs
# [program:worker_projection]
# command=php /var/www/html/bin/consume projection_group