<?php

declare(strict_types=1);

namespace Vortos\Iac\Terraform;

use Vortos\Foundation\Config\Env;
use Vortos\Iac\Exception\IacException;
use Vortos\Iac\Exception\SecretLiteralException;

/**
 * Builder + renderer for one Terraform JSON (.tf.json) file.
 *
 * Renders deterministically: keys sorted, stable pretty-printing, trailing
 * newline — same input is always byte-identical output, which is what makes
 * `vortos:iac:export --check` an exact CI drift guard.
 *
 * The secret gate lives here, not in exporters, so no exporter can bypass
 * it: literal strings assigned to secret-looking attribute names fail the
 * export unless the attribute path was explicitly allow-listed on the
 * definition (loud, greppable, reviewable).
 */
final class TerraformDocument
{
    public const GENERATED_MARKER = 'GENERATED by vortos:iac:export';

    private const IDENTIFIER_PATTERN = '/^[A-Za-z_][A-Za-z0-9_-]*$/';

    /** @var array<string, array{source: string, version: string}> */
    private array $requiredProviders = [];

    /** @var array<string, array<string, array<string, mixed>>> type → label → attrs */
    private array $resources = [];

    /** @var array<string, TfVariable> */
    private array $variables = [];

    /** @var array<string, mixed>|null backend block: e.g. ['s3' => [...]] */
    private ?array $backend = null;

    /** @var array<string, mixed> extra terraform{} block settings (e.g. required_version) */
    private array $terraformSettings = [];

    public function __construct(
        /** @var list<string> dotted attribute paths allowed to hold secret-looking literals */
        private readonly array $allowedLiteralPaths = [],
    ) {}

    public function requiredProvider(string $localName, string $source, string $version): void
    {
        $this->assertIdentifier($localName, 'provider local name');
        $this->requiredProviders[$localName] = ['source' => $source, 'version' => $version];
    }

    /** @param array<string, mixed> $attributes values: scalars, arrays, or TfValueInterface */
    public function resource(string $type, string $label, array $attributes): void
    {
        $this->assertIdentifier($type, 'resource type');
        $this->assertIdentifier($label, 'resource label');

        if (isset($this->resources[$type][$label])) {
            throw new IacException(sprintf(
                "Duplicate Terraform resource '%s.%s' — resource labels must be unique per type.",
                $type,
                $label,
            ));
        }

        $this->guardSecrets($attributes, '');
        $this->resources[$type][$label] = $this->normalize($attributes);
    }

    /** @param array<string, mixed> $config backend configuration attributes (no secrets!) */
    public function backend(string $type, array $config): void
    {
        $this->assertIdentifier($type, 'backend type');
        $this->guardSecrets($config, 'backend');
        $this->backend = [$type => $this->normalize($config)];
    }

    /** @param array<string, mixed> $settings extra terraform{} block settings */
    public function terraformBlock(array $settings): void
    {
        $this->terraformSettings = array_merge($this->terraformSettings, $settings);
    }

    /** Registers a variable; identical re-registration is a no-op, conflicting specs fail. */
    public function variable(TfVariable $variable): void
    {
        $existing = $this->variables[$variable->name] ?? null;

        if ($existing !== null && $existing->block() !== $variable->block()) {
            throw new IacException(sprintf(
                "Conflicting definitions for Terraform variable '%s'.",
                $variable->name,
            ));
        }

        $this->variables[$variable->name] = $variable;
    }

    public function hasVariables(): bool
    {
        return $this->variables !== [];
    }

    /** A document holding only this document's variable blocks (for the variables file). */
    public function variablesDocument(): self
    {
        $doc = new self();
        foreach ($this->variables as $variable) {
            $doc->variable($variable);
        }
        return $doc;
    }

    public function render(bool $includeVariables = true): string
    {
        $body = ['//' => self::GENERATED_MARKER . ' — do not edit; change your InfraConfig and re-export.'];

        $terraformBlock = [];

        if ($this->requiredProviders !== []) {
            $providers = $this->requiredProviders;
            ksort($providers);
            $terraformBlock['required_providers'] = $providers;
        }

        if ($this->backend !== null) {
            $terraformBlock['backend'] = $this->backend;
        }

        foreach ($this->terraformSettings as $key => $value) {
            $terraformBlock[$key] = $value;
        }

        if ($terraformBlock !== []) {
            ksort($terraformBlock);
            $body['terraform'] = $terraformBlock;
        }

        if ($this->resources !== []) {
            $resources = [];
            foreach ($this->resources as $type => $byLabel) {
                ksort($byLabel);
                $resources[$type] = $byLabel;
            }
            ksort($resources);
            $body['resource'] = self::sortDeep($resources);
        }

        if ($includeVariables && $this->variables !== []) {
            $variables = [];
            foreach ($this->variables as $name => $variable) {
                $variables[$name] = $variable->block();
            }
            $body['variable'] = self::sortDeep($variables);
        }

        return json_encode(
            $body,
            JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_THROW_ON_ERROR,
        ) . "\n";
    }

    /** Recursively converts attribute values to their JSON form. */
    private function normalize(array $attributes): array
    {
        $out = [];

        foreach ($attributes as $key => $value) {
            $out[$key] = match (true) {
                $value instanceof TfValueInterface => $value->toJsonValue(),
                is_array($value) => $this->normalize($value),
                default => (new TfLiteral($value))->toJsonValue(),
            };
        }

        return $out;
    }

    private function guardSecrets(array $attributes, string $pathPrefix): void
    {
        foreach ($attributes as $key => $value) {
            $path = $pathPrefix === '' ? (string) $key : $pathPrefix . '.' . $key;

            if ($value instanceof Env) {
                throw new IacException(sprintf(
                    "Raw Env reference reached the Terraform document at '%s' — exporters must translate Env to TfVariable first.",
                    $path,
                ));
            }

            if (is_array($value)) {
                $this->guardSecrets($value, $path);
                continue;
            }

            $isLiteralString = is_string($value)
                || ($value instanceof TfLiteral && is_string($value->value));

            if (
                $isLiteralString
                && preg_match(TfVariable::SECRET_NAME_PATTERN, (string) $key)
                && !in_array($path, $this->allowedLiteralPaths, true)
            ) {
                throw new SecretLiteralException(sprintf(
                    "Attribute '%s' looks like a secret but holds a literal value. "
                    . 'Use Env::string(...) in the resource definition (it becomes a sensitive Terraform variable), '
                    . "or explicitly opt out with ->allowLiteral('%s') on the exporter definition.",
                    $path,
                    $path,
                ));
            }
        }
    }

    private function assertIdentifier(string $value, string $what): void
    {
        if (!preg_match(self::IDENTIFIER_PATTERN, $value)) {
            throw new IacException(sprintf("Invalid Terraform %s '%s'.", $what, $value));
        }
    }

    private static function sortDeep(array $value): array
    {
        foreach ($value as &$v) {
            if (is_array($v)) {
                $v = self::sortDeep($v);
            }
        }
        unset($v);

        if (!array_is_list($value)) {
            ksort($value);
        }

        return $value;
    }
}
