<?php

declare(strict_types=1);

use Vortos\Auth\DependencyInjection\VortosAuthConfig;
use Vortos\Auth\Jwt\Key\KeyStatus;
use Vortos\Auth\Lockout\LockoutConfig;
use Vortos\Auth\Lockout\LockoutTrack;
use Vortos\Auth\Quota\QuotaFailureMode;
use Vortos\Auth\Storage\InMemoryTokenStorage;
use Vortos\Auth\Storage\RedisTokenStorage;

// Infrastructure driver is chosen via ENV — configure behaviour here.
//
// VORTOS_AUTH_*  env vars are not read here; the options below are the
// canonical way to tune auth behaviour across environments.
//
// For per-environment overrides create config/{env}/auth.php — it is
// loaded after this file and any value set there wins.

return static function (VortosAuthConfig $config): void {
    $config
        // JWT signing keys (a "keyring").
        //
        // Tokens are signed by the single Active key and verified against EVERY
        // key in the ring (matched by the token's `kid` header). That is what
        // makes key rotation zero-downtime — see the rotation runbook below.
        //
        // HS256 — single shared secret. Simple, good for single-service apps.
        //   Set JWT_SECRET in .env (generated by vortos:setup).
        //   Generate a safe value: bin2hex(random_bytes(32))
        ->hs256($_ENV['JWT_SECRET'] ?? '', kid: 'default')

        // RS256 — asymmetric key pair. Better for multi-service apps — verifying
        //   services only need the public key and can never forge tokens. Generate:
        //     php bin/console vortos:auth:keys:generate --out=/run/secrets --kid=2026-06
        //   Store PEM files outside the project root and never commit them.
        // Uncomment to use RS256 instead (remove ->hs256(...) above):
        // ->rs256FromPaths(
        //     $_ENV['JWT_KID'] ?? '2026-06',
        //     $_ENV['JWT_PRIVATE_KEY_PATH'] ?? '',
        //     $_ENV['JWT_PUBLIC_KEY_PATH'] ?? '',
        // )
        // Publish public keys at /.well-known/jwks.json (RS256 only):
        // ->jwks(true)

        // --- Key rotation runbook (RS256) ---------------------------------------
        // 1. ADD: keep the current key Active, add the new one as Next.
        //      ->rs256FromPaths('2026-06', ..., status: KeyStatus::Active)
        //      ->rs256FromPaths('2026-09', ..., status: KeyStatus::Next)
        //    Deploy. Now every instance VERIFIES the new key (no token signs with it yet).
        // 2. PROMOTE: make the new key Active and the old one Retiring.
        //      ->rs256FromPaths('2026-06', ..., status: KeyStatus::Retiring)
        //      ->rs256FromPaths('2026-09', ..., status: KeyStatus::Active)
        //    Deploy. New tokens sign with the new key; old tokens still verify.
        // 3. DROP: once max(refreshTokenTtl) has elapsed (no token signed by the old
        //    key can still be alive), remove the Retiring key entirely. Deploy.
        // KeyStatus is imported above; run `vortos:auth:keys:list` to inspect the ring.
        // ------------------------------------------------------------------------

        // Access token lifetime in seconds.
        // Keep short — a stolen access token is valid for this long.
        // 900 = 15 minutes (recommended for most APIs)
        ->accessTokenTtl(900)

        // Refresh token lifetime in seconds.
        // 604800 = 7 days. Slide or shorten for higher-security contexts.
        ->refreshTokenTtl(604800)

        // Claim embedded in the JWT 'iss' field.
        // Use your app name — useful when multiple services share a key.
        ->issuer($_ENV['APP_NAME'] ?? 'vortos')

        // Token storage backend.
        //
        // InMemoryTokenStorage — no persistence across requests (fine for testing).
        // RedisTokenStorage    — persistent; required for forced logout and
        //                        multi-process deployments (FrankenPHP workers).
        //                        Requires Redis and vortos/vortos-cache.
        ->tokenStorage(InMemoryTokenStorage::class)

        // Quota/rate-limit response behavior.
        // fail_closed is safest for cost-sensitive quotas; use fail_open in
        // local/dev if availability is more important than enforcement.
        ->quotaFailureMode(QuotaFailureMode::FailClosed)
        ->quotaHeaders(true)
        ->rateLimitHeaders(true)
        ->problemDetails(true)
    ;

    // Account lockout after repeated failed logins.
    // Remove this block to disable lockout entirely.
    // Requires Redis (RedisTokenStorage or vortos/vortos-cache).
    //
    // $config->lockout()
    //     // Lock the account after this many consecutive failures.
    //     ->maxAttempts(5)
    //     // How long the account stays locked, in seconds. 900 = 15 min.
    //     ->lockDurationSeconds(900)
    //     // Track failures by email, IP address, or both.
    //     ->trackBy(LockoutTrack::Email)
    //     // Message shown to the user while locked out.
    //     ->message('Account locked due to too many failed attempts. Try again later.')
    // ;
};
