<?php

declare(strict_types=1);

namespace Vortos\Backup\Schedule;

use Vortos\Backup\Console\BackupDrillCommand;
use Vortos\Backup\Domain\BackupKind;

/**
 * Renders declared {@see BackupSchedule}s into a managed crontab fragment that invokes
 * `vortos backup:run`. The framework owns the bytes between the managed markers, so the
 * fragment is regenerable and diffable (the same idiom `vortos-docker` uses for
 * Supervisor worker programs) — the actual trigger lives on the host, not in-app.
 */
final class CronFragmentGenerator
{
    private const BEGIN = '# <vortos-backup-schedules>';
    private const END = '# </vortos-backup-schedules>';

    public function __construct(
        private readonly string $binaryPath = '/usr/local/bin/vortos',
        private readonly string $runAsUser = '',
    ) {}

    /**
     * @param list<BackupSchedule> $schedules
     */
    public function generate(array $schedules): string
    {
        $lines = [self::BEGIN, '# Generated by vortos-backup. Do not edit between these markers.'];

        foreach ($schedules as $schedule) {
            $user = $this->runAsUser === '' ? '' : $this->runAsUser . ' ';
            $lines[] = sprintf(
                '%s %s%s %s  # %s',
                $schedule->cron,
                $user,
                $this->binaryPath,
                $this->commandFor($schedule),
                $schedule->name,
            );
        }

        $lines[] = self::END;

        return implode("\n", $lines) . "\n";
    }

    /**
     * The full console command (verb + args) for a schedule. R8-6: retention/drill no longer collapse
     * to backup:run — each type emits its own verb. Backup carries --kind (a restore-point kind);
     * retention is engine+env scoped.
     *
     * A DRILL CARRIES ITS KIND TOO, in BOTH directions, and omitting it is not cosmetic.
     * `backup:drill` with no kind restores the newest artifact it can — of any kind. Which one that
     * is depends on the relative timing of two independent cadences, so the emitted line does not
     * reliably drill anything in particular:
     *
     *   - omitted on a point-in-time schedule, it picks the frequent logical dump and reports green
     *     for a WAL chain it never touched;
     *   - omitted on a logical schedule, it picks the base backup whenever one is newer — which was
     *     observed on production, where a plain `backup:drill` chose a base backup four hours newer
     *     than the latest dump and spent two minutes replaying WAL the daily drill is not for.
     *
     * Both names come from the command class so a generated crontab cannot drift from the options
     * that command actually registers.
     */
    private function commandFor(BackupSchedule $schedule): string
    {
        return match ($schedule->type) {
            BackupScheduleType::Backup => sprintf(
                'backup:run --engine=%s --kind=%s --env=%s',
                $schedule->engine->value,
                $schedule->kind->value,
                $schedule->environment,
            ),
            BackupScheduleType::Retention => sprintf(
                'backup:retention --engine=%s --env=%s --apply',
                $schedule->engine->value,
                $schedule->environment,
            ),
            BackupScheduleType::Drill => sprintf(
                '%s --engine=%s --env=%s %s',
                BackupDrillCommand::NAME,
                $schedule->engine->value,
                $schedule->environment,
                // --pitr for the physical path because that is the name operators know it by; the
                // general --kind for everything else. They mean the same thing to the command.
                $schedule->kind === BackupKind::PhysicalBase
                    ? '--' . BackupDrillCommand::OPTION_PITR
                    : '--' . BackupDrillCommand::OPTION_KIND . '=' . $schedule->kind->value,
            ),
        };
    }
}
