<?php

declare(strict_types=1);

namespace Vortos\Backup\Schedule;

/**
 * Renders declared {@see BackupSchedule}s into a managed crontab fragment that invokes
 * `vortos backup:run`. The framework owns the bytes between the managed markers, so the
 * fragment is regenerable and diffable (the same idiom `vortos-docker` uses for
 * Supervisor worker programs) — the actual trigger lives on the host, not in-app.
 */
final class CronFragmentGenerator
{
    private const BEGIN = '# <vortos-backup-schedules>';
    private const END = '# </vortos-backup-schedules>';

    public function __construct(
        private readonly string $binaryPath = '/usr/local/bin/vortos',
        private readonly string $runAsUser = '',
    ) {}

    /**
     * @param list<BackupSchedule> $schedules
     */
    public function generate(array $schedules): string
    {
        $lines = [self::BEGIN, '# Generated by vortos-backup. Do not edit between these markers.'];

        foreach ($schedules as $schedule) {
            $user = $this->runAsUser === '' ? '' : $this->runAsUser . ' ';
            $lines[] = sprintf(
                '%s %s%s backup:run --engine=%s --kind=%s --env=%s  # %s',
                $schedule->cron,
                $user,
                $this->binaryPath,
                $schedule->engine->value,
                $schedule->kind->value,
                $schedule->environment,
                $schedule->name,
            );
        }

        $lines[] = self::END;

        return implode("\n", $lines) . "\n";
    }
}
