<?php

declare(strict_types=1);

namespace Vortos\Iac\Tests\Export;

use PHPUnit\Framework\TestCase;
use Vortos\Iac\Exception\PathViolationException;
use Vortos\Iac\Export\FileOutcome;
use Vortos\Iac\Export\SafeFileWriter;
use Vortos\Iac\Terraform\TerraformDocument;

final class SafeFileWriterTest extends TestCase
{
    private string $projectDir;
    private SafeFileWriter $writer;

    protected function setUp(): void
    {
        $this->projectDir = sys_get_temp_dir() . '/vortos-iac-writer-' . uniqid();
        mkdir($this->projectDir, 0755, true);
        $this->writer = new SafeFileWriter($this->projectDir);
    }

    protected function tearDown(): void
    {
        if (is_dir($this->projectDir)) {
            $items = new \RecursiveIteratorIterator(
                new \RecursiveDirectoryIterator($this->projectDir, \FilesystemIterator::SKIP_DOTS),
                \RecursiveIteratorIterator::CHILD_FIRST,
            );
            foreach ($items as $item) {
                $item->isDir() ? rmdir($item->getPathname()) : unlink($item->getPathname());
            }
            rmdir($this->projectDir);
        }
    }

    private function generated(string $body = '{}'): string
    {
        return '{"//": "' . TerraformDocument::GENERATED_MARKER . '"}' . "\n";
    }

    public function test_write_creates_file_and_reports_written(): void
    {
        $outcome = $this->writer->write('infra/a.tf.json', $this->generated());

        $this->assertSame(FileOutcome::Written, $outcome);
        $this->assertFileExists($this->projectDir . '/infra/a.tf.json');
        $this->assertSame(0644, fileperms($this->projectDir . '/infra/a.tf.json') & 0777);
    }

    public function test_identical_rewrite_reports_unchanged(): void
    {
        $this->writer->write('infra/a.tf.json', $this->generated());

        $this->assertSame(FileOutcome::Unchanged, $this->writer->write('infra/a.tf.json', $this->generated()));
    }

    public function test_refuses_to_overwrite_non_generated_file(): void
    {
        mkdir($this->projectDir . '/infra');
        file_put_contents($this->projectDir . '/infra/handwritten.tf.json', '{"resource": {}}');

        $this->expectException(PathViolationException::class);
        $this->expectExceptionMessage('was not generated by vortos:iac:export');

        $this->writer->write('infra/handwritten.tf.json', $this->generated());
    }

    public function test_check_reports_drift_for_missing_and_differing_files(): void
    {
        $this->assertSame(FileOutcome::Drift, $this->writer->check('infra/missing.tf.json', $this->generated()));

        $this->writer->write('infra/a.tf.json', $this->generated());
        file_put_contents($this->projectDir . '/infra/a.tf.json', $this->generated() . '// drifted');

        $this->assertSame(FileOutcome::Drift, $this->writer->check('infra/a.tf.json', $this->generated()));
    }

    public function test_check_reports_unchanged_when_identical(): void
    {
        $this->writer->write('infra/a.tf.json', $this->generated());

        $this->assertSame(FileOutcome::Unchanged, $this->writer->check('infra/a.tf.json', $this->generated()));
    }

    public function test_no_temp_files_left_behind(): void
    {
        $this->writer->write('infra/a.tf.json', $this->generated());

        $this->assertCount(1, glob($this->projectDir . '/infra/*'), 'Atomic write must leave no temp droppings');
    }

    public function test_write_outside_project_is_rejected(): void
    {
        $this->expectException(PathViolationException::class);

        $this->writer->write('../escape.tf.json', $this->generated());
    }
}
